language:
  - php
php:
  - 5.5

before_install:
  - sudo apt-get update > /dev/null

before_script:
  - sudo apt-get install -qq npm
  - npm install -g jshint
  - pear config-set auto_discover 1
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - git clone git://github.com/typo3-ci/TYPO3SniffPool.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/TYPO3SniffPool
  - git clone git://github.com/typo3-ci/TYPO3CMS.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/TYPO3CMS
  - sed -i 's/<rule ref="..\/TYPO3SniffPool\/Sniffs\/Files\/FilenameSniff.php" \/>/<!--<rule ref="..\/TYPO3SniffPool\/Sniffs\/Files\/FilenameSniff.php" \/> -->/' $(pear config-get php_dir)/PHP/CodeSniffer/Standards/TYPO3CMS/ruleset.xml
script:
  - find . \( -name '*.php' -o -name '*.inc' -o -name '*.phtml' \) -exec php -lf {} \;
  - phpcs -s -n --standard=TYPO3CMS --extensions=php --ignore='lib/laterpay/*,lib/browscap/*,cache/*' ./
  - jshint ./asset_sources

notifications:
  slack: laterpay:3DYypQbldQxT4cbSs5ytZA3D
  email:
    on_success: change
    on_failure: change
