language:
  - php
php:
  - 5.5

before_install:
  - sudo apt-get update > /dev/null

before_install:
  - sudo apt-get update
before_script:
  - pear config-set auto_discover 1
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - git clone git://github.com/typo3-ci/TYPO3SniffPool.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/TYPO3SniffPool
  - git clone git://github.com/typo3-ci/TYPO3CMS.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/TYPO3CMS
script:
  - find . \( -name '*.php' -o -name '*.inc' \) -exec php -lf {} \;
  - phpcs -s -n --standard=TYPO3CMS .	

notifications:
  email:
    on_success: change
    on_failure: change	