<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>
<?php error_log (print_r($laterpay, true).PHP_EOL, 3, '/vagrant/main_form.log');?>
<div class="lp_page">

    <div id="lp_js_flashMessage" class="lp_flashMessage" style="display:none;">
        <p></p>
    </div>

    <div class="lp_pagewrap">
        <div class="lp_row lp_u_clearfix">
            <h2><?php tx_laterpay_helper_string::trEcho('Preview of Paid Content'); ?></h2>
            <form id="lp_js_previewModeForm" method="post">
                <input type="hidden" name="form"    value="paid_content_preview">
                <input type="hidden" name="action"  value="laterpay_appearance">
                <?php if ( function_exists( 'wp_nonce_field' ) ) { wp_nonce_field('laterpay_form'); } ?>
                <label class="lp_u_left">
                    <input type="radio"
                            name="paid_content_preview"
                            value="1"
                            class="lp_js_togglePreviewMode lp_js_styleInput"
                            <?php if ( $laterpay['show_teaser_content_only'] ): ?>checked<?php endif; ?>/>
                    <?php tx_laterpay_helper_string::trEcho('Teaser content only'); ?>
                    <div class="lp_previewMode-1"></div>
                </label>
                <label class="lp_u_left">
                    <input type="radio"
                            name="paid_content_preview"
                            value="0"
                            class="lp_js_togglePreviewMode lp_js_styleInput"
                            <?php if ( ! $laterpay['show_teaser_content_only'] ): ?>checked<?php endif; ?>/>
                    <?php tx_laterpay_helper_string::trEcho('Teaser content + full content, covered by overlay'); ?>
                    <div class="lp_previewMode-2"></div>
                </label>
            </form>
        </div>
        <hr class="lp_u_m-1-0 lp_u_m-b3">
		
        <div class="lp_row">
            <h2><?php tx_laterpay_helper_string::trEcho('Auto-teaser configuration'); ?></h2>
        </div>

		<form id="lp_js_autoTeaserContent" method="post">
			<input type="hidden" name="form" value="auto_teaser_configuration">
			<input type="hidden" name="action" value="laterpay_appearance">

			<table>
				<tr>
					<td>
						<label><?php tx_laterpay_helper_string::trEcho('Percentage of Content')?></label>
					</td>
					<td>
						<input class="lp_input" name="teaser_percentage_of_content" type="text" value="<?php echo $laterpay['teaser_percentage_of_content']?>">
						<span name="teaser_percentage_of_content"></span>
					</td>
				</tr>
				<tr>
					<td>
						<label><?php tx_laterpay_helper_string::trEcho('Minimum words count')?></label>
					</td>
					<td>
						<input class="lp_input" name="teaser_min_words_count" type="text" value="<?php echo $laterpay['teaser_min_words_count']?>">
						<span name="teaser_min_words_count"></span>
					</td>
				</tr>
				<tr>
					<td>
						<label><?php tx_laterpay_helper_string::trEcho('Maximum words count')?></label>
					</td>
					<td>
						<input class="lp_input" name="teaser_max_words_count" type="text" value="<?php echo $laterpay['teaser_max_words_count']?>">
						<span name="teaser_max_words_count"></span>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<a data-icon="f" class="lp_editLink lp_saveLink lp_u_inlineBlock lp_u_m-l1 lp_u_pd-0-05" id="lp_js_AutoTeaserContentSave" href="#"><?php tx_laterpay_helper_string::trEcho('Save')?></a>
					</td>
				</tr>
			</table>
		</form>
	    <hr class="lp_u_m-1-0 lp_u_m-b3">

	    <div class="lp_row">
		    <h2><?php tx_laterpay_helper_string::trEcho('User groups with grunted admin rights'); ?></h2>
	    </div>

	    <form id="lp_js_AdminUserRoles" method="post">
		    <input type="hidden" name="form" value="admin_user_roles_configuration">
		    <input type="hidden" name="action" value="laterpay_appearance">

		    <table>
			    <tr>
				    <td>
					    <label><?php tx_laterpay_helper_string::trEcho('User Groups:')?></label>
				    </td>
				    <td>
					    <select name="admin_user_roles[]" multiple="multiple">
						    <?php foreach( $laterpay['admin_user_roles_collection'] as $role ): ?>
						        <option value="<?php echo $role['uid']; ?>" <?php if ( in_array( $role['uid'], $laterpay['admin_user_roles'] ) ) echo 'selected'; ?> ><?php echo $role['title']; ?></option>
						    <?php endforeach; ?>
					    </select>
					    <span name="admin_user_roles"></span>
				    </td>
			    </tr>
			    <tr>
				    <td colspan="2">
					    <a data-icon="f" class="lp_editLink lp_saveLink lp_u_inlineBlock lp_u_m-l1 lp_u_pd-0-05" id="lp_js_AdminUserRolesSave" href="#"><?php tx_laterpay_helper_string::trEcho('Save')?></a>
				    </td>
			    </tr>
		    </table>
	    </form>
    </div>

</div>
