<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<div class="lp_page wp-core-ui">

    <div id="lp_js_flashMessage" class="lp_flashMessage" style="display:none;">
        <p></p>
    </div>

    <div class="lp_wrap">
        <div id="lp_js_standardKpiTab">
            <h1><?php
                echo sprintf(
                         tx_laterpay_helper_string::tr('%s Dashboard of %s Sales from%s'),
                        $this->getTextView( 'backend/partials/dropdown_interval' ),
                        $this->getTextView( 'backend/partials/dropdown_sales' ),
                        $this->getTextView( 'backend/partials/navigation_interval' )
                );
               ?>
            </h1>

            <div class="lp_row">
                <div class="lp_u_w-1-3">
                    <h2><?php tx_laterpay_helper_string::trEcho('Conversion'); ?></h2>
                    <div id="lp_js_conversionDiagram" class="lp_dashboardGraph"></div>
                    <div class="lp_statisticsRow lp_u_clearfix">
                        <ul>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Number of times a page with purchasable content has been viewed in selected interval'); ?>">
                                <big><span id="lp_js_totalImpressions">0</span></big>
                                <?php tx_laterpay_helper_string::trEcho('Views'); ?>
                            </li>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Share of purchases of all page views of pages with purchasable content'); ?>">
                                <big><span id="lp_js_avgConversion">0.0</span><small>%</small></big>
                                <?php tx_laterpay_helper_string::trEcho('Conversion'); ?>
                            </li>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Share of new buyers of all buyers in selected interval'); ?>">
                                <big><span id="lp_js_shareOfNewCustomers">0</span><small>%</small></big>
                                <?php tx_laterpay_helper_string::trEcho('New Customers'); ?>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="lp_u_w-1-3">
                    <h2><?php tx_laterpay_helper_string::trEcho('Items Sold'); ?></h2>
                    <div id="lp_js_salesDiagram" class="lp_dashboardGraph"></div>
                    <div class="lp_statisticsRow lp_u_clearfix">
                        <ul>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Average number of items sold per day in selected interval'); ?>">
                                <big><span id="lp_js_avg-items-sold">0.0</span></big>
                                <?php tx_laterpay_helper_string::trEcho('AVG Items Sold'); ?>
                            </li>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total number of items sold in selected interval'); ?>">
                                <big><span id="lp_js_total-items-sold">0</span></big>
                                <?php tx_laterpay_helper_string::trEcho('Items Sold'); ?>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="lp_u_w-1-3">
                    <h2><?php tx_laterpay_helper_string::trEcho('Committed Revenue'); ?></h2>
                    <div id="lp_js_revenueDiagram" class="lp_dashboardGraph"></div>
                    <div class="lp_statisticsRow lp_u_clearfix">
                        <ul>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Average value of items sold in selected interval'); ?>">
                                <big><span id="lp_js_avgRevenue">0.00</span><small><?php echo $laterpay['currency']; ?></small></big>
                                <?php tx_laterpay_helper_string::trEcho('AVG Purchase'); ?>
                            </li>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total value of items sold in selected interval'); ?>">
                                <big><span id="lp_js_totalRevenue">0.00</span><small><?php echo $laterpay['currency']; ?></small></big>
                                <?php tx_laterpay_helper_string::trEcho('Committed Revenue'); ?>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="lp_row">
                <div class="lp_u_w-1-3">
                    <h3><?php tx_laterpay_helper_string::trEcho('Best-converting Items'); ?></h3>
                    <ol id="lp_js_bestConvertingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                    <h3><?php tx_laterpay_helper_string::trEcho('Least-converting Items'); ?></h3>
                    <ol id="lp_js_leastConvertingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                </div>
                <div class="lp_u_w-1-3">
                    <h3><?php tx_laterpay_helper_string::trEcho('Most-selling Items'); ?></h3>
                    <ol id="lp_js_bestSellingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                    <h3><?php tx_laterpay_helper_string::trEcho('Least-selling Items'); ?></h3>
                    <ol id="lp_js_leastSellingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                </div>
                <div class="lp_u_w-1-3">
                    <h3><?php tx_laterpay_helper_string::trEcho('Most Revenue-generating Items'); ?></h3>
                    <ol id="lp_js_bestGrossingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                    <h3><?php tx_laterpay_helper_string::trEcho('Least Revenue-generating Items'); ?></h3>
                    <ol id="lp_js_leastGrossingList" class="lp_topBottomList">
                        <dfn><?php tx_laterpay_helper_string::trEcho('No data available'); ?></dfn>
                    </ol>
                </div>
            </div>
        </div>

        <div id="lp_js_timePassesKpiTab" style="display:none;">
            <h1 style="line-height:1.4em;"><?php tx_laterpay_helper_string::trEcho('Time Pass Customer Lifecycle'); ?></h1>

            <div class="lp_time-pass-lifecycle lp_u_clearfix">
                <div class="lp_time-pass-lifecycle__kpi lp_u_w-1-4 lp_u_left">
                    <h2><?php tx_laterpay_helper_string::trEcho('All Time Passes'); ?></h2>

                    <div class="lp_statisticsRow lp_u_clearfix">
                        <ul class="lp_u_clearfix">
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total number of sold time passes'); ?>">
                                <big><?php echo $laterpay['passes']['summary']['sold']; ?></big>
                                <?php tx_laterpay_helper_string::trEcho('Sold'); ?>
                            </li>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total number of active time passes'); ?>">
                                <big><?php echo $laterpay['passes']['summary']['active']; ?></big>
                                <?php tx_laterpay_helper_string::trEcho('Active'); ?>
                            </li>
                            <?php if ( isset( $laterpay['passes']['summary']['unredeemed'] ) ): ?>
                                <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total number of unredeemed time pass vouchers'); ?>">
                                    <big><?php echo $laterpay['passes']['summary']['unredeemed']; ?></big>
                                    <?php tx_laterpay_helper_string::trEcho('Unredeemed'); ?>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <ul>
                            <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Total value of sold time passes'); ?>">
                                <big><?php echo $laterpay['passes']['summary']['committed_revenue']; ?><small><?php echo $laterpay['currency']; ?></small></big>
                                <?php tx_laterpay_helper_string::trEcho('Committed Revenue'); ?>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="lp_u_w-3-4 lp_u_left">
                    <div class="lp_js_timepassDiagram lp_dashboardGraph" data-id="0" style="width:600px;"></div>
                </div>
            </div>

            <?php if ( isset( $laterpay['passes']['individual'] ) ): ?>
                <?php foreach( $laterpay['passes']['individual'] as $pass_id => $pass ): ?>
                    <div class="lp_time-pass-lifecycle lp_u_clearfix">
                        <div class="lp_time-pass-lifecycle__kpi lp_u_w-1-4 lp_u_left">
                            <h2><?php echo sprintf( tx_laterpay_helper_string::tr('Time pass \'%s\''), $pass['data']['title'] ); ?></h2>
                            <dfn><?php echo tx_laterpay_helper_timepass::getDescription( $pass['data'], true ); ?></dfn>

                            <div class="lp_statisticsRow lp_u_clearfix">
                                <ul class="lp_u_clearfix">
                                    <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Number of sold time passes'); ?>">
                                        <big><?php echo $pass['sold']; ?></big>
                                        <?php tx_laterpay_helper_string::trEcho('Sold'); ?>
                                    </li>
                                    <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Number of active time passes'); ?>">
                                        <big><?php echo $pass['active']; ?></big>
                                        <?php tx_laterpay_helper_string::trEcho('Active'); ?>
                                    </li>
                                    <?php if ( isset( $pass['unredeemed'] ) ): ?>
                                        <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Number of unredeemed time pass vouchers'); ?>">
                                            <big><?php echo $pass['unredeemed']; ?></big>
                                            <?php tx_laterpay_helper_string::trEcho('Unredeemed'); ?>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                                <ul>
                                    <li class="lp_tooltip" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Value of sold time passes'); ?>">
                                        <big><?php echo $pass['committed_revenue']; ?><small><?php echo $laterpay['currency']; ?></small></big>
                                        <?php tx_laterpay_helper_string::trEcho('Committed Revenue'); ?>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="lp_u_w-3-4 lp_u_left">
                            <div class="lp_js_timepassDiagram lp_dashboardGraph" data-id="<?php echo $pass_id; ?>" style="width:600px;"></div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

    </div>

</div>
