<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>
<div class="lp_page">

    <div id="lp_js_flashMessage" class="lp_flashMessage" style="display:none;">
        <p></p>
    </div>

    <div class="lp_pagewrap">

        <div class="lp_row">
            <h2><?php tx_laterpay_helper_string::trEcho('Individual Prices'); ?></h2>

            <dfn class="lp_u_block lp_u_m-b1">
                <?php tx_laterpay_helper_string::trEcho('You can set individual prices for posts, when adding or editing a post.'); ?>
            </dfn>
        </div>

        <div class="lp_row lp_u_m-t3">
            <h2 id="lp_timePasses"><?php tx_laterpay_helper_string::trEcho('Time Passes'); ?></h2>

            <dfn class="lp_u_block lp_u_m-b1">
                <?php tx_laterpay_helper_string::trEcho('Time passes provide access to your entire site or specific categories for a limited time.'); ?>
            </dfn>

            <div class="lp_js_timePassEditor lp_timePassEditor">
                <a href="#" id="lp_js_addTimePass" class="lp_addTimePass button button-primary" data-icon="c"><?php tx_laterpay_helper_string::trEcho('New Time Pass'); ?></a>

                <?php foreach ( $laterpay['passes_list'] as $pass ): ?>
                    <div class="lp_js_timePassWrapper lp_timePassWrapper lp_u_clearfix lp_u_m-t1" data-pass-id="<?php echo $pass['pass_id']; ?>">
                        <div class="lp_timePass__idWrapper">
                            <?php tx_laterpay_helper_string::trEcho('Pass'); ?>
                            <span class="lp_js_timePassId lp_timePass__id"><?php echo $pass['pass_id']; ?></span>
                        </div>
                        <div class="lp_js_timePassPreview lp_u_left">
                            <?php echo $this->renderTimePass( (array) $pass ); ?>
                        </div>

                        <div class="lp_js_timePass_editorContainer lp_timePass_editorContainer lp_u_m-t05"></div>

                        <a href="#" class="lp_js_saveTimePass lp_saveLink button button-primary lp_u_hide"><?php tx_laterpay_helper_string::trEcho('Save'); ?></a>
                        <a href="#" class="lp_js_cancelEditingTimePass lp_cancelLink lp_u_inlineBlock lp_u_pd-05 lp_u_hide" data-icon="e"><?php tx_laterpay_helper_string::trEcho('Cancel'); ?></a>
                        <a href="#" class="lp_js_editTimePass lp_changeLink lp_u_inlineBlock lp_u_pd-05" data-icon="d"><?php tx_laterpay_helper_string::trEcho('Change'); ?></a><br>
                        <a href="#" class="lp_js_deleteTimePass lp_deleteLink lp_u_inlineBlock lp_u_pd-05" data-icon="g"><?php tx_laterpay_helper_string::trEcho('Delete'); ?></a>

                        <div class="lp_js_voucherList lp_voucherList">
                            <?php if ( isset( $laterpay['vouchers_list'][ $pass['pass_id']] ) ) : ?>
                                <?php foreach ( $laterpay['vouchers_list'][ $pass['pass_id']] as $voucher_code => $voucher_price ): ?>
                                    <div class="lp_js_voucher lp_voucherRow">
                                        <span class="lp_voucherCodeLabel"><?php echo $voucher_code; ?></span>
                                        <span class="lp_voucherCodeInfos">
                                        <?php tx_laterpay_helper_string::trEcho('allows purchasing this pass for'); ?>
                                            <?php echo $voucher_price . ' ' . $laterpay['standard_currency']; ?>.<br>
                                            <?php
                                                echo ( ! isset( $laterpay['vouchers_statistic'][$pass['pass_id']][$voucher_code] ) ) ?
                                                    0 :
                                                    $laterpay['vouchers_statistic'][$pass['pass_id']][$voucher_code];
                                            ?>
                                            <?php tx_laterpay_helper_string::trEcho('times redeemed.'); ?>
                                        </span>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>

                <div id="lp_js_timePassTemplate" class="lp_js_timePassWrapper lp_js_addTimePassWrapper lp_timePassWrapper lp_u_clearfix lp_u_hide" data-pass-id="0">
                    <div class="lp_timePass__idWrapper" style="display:none;">
                        <?php tx_laterpay_helper_string::trEcho('Pass'); ?>
                        <span class="lp_js_timePassId lp_timePass__id">x</span>
                    </div>

                    <div class="lp_js_timePassPreview lp_u_left">
                        <?php echo $this->renderTimePass(); ?>
                    </div>

                    <div class="lp_js_timePass_editorContainer lp_timePass_editorContainer lp_u_m-t05">
                        <form id="lp_js_timePassFormTemplate" class="lp_js_timePassEditor_form lp_timePassEditor_form lp_u_hide lp_u_clearfix" method="post">
                            <input type="hidden" name="form" value="time_pass_form_save">
                            <input type="hidden" name="action" value="laterpay_pricing">
                            <input type="hidden" name="pass_id" value="0" id="lp_js_timePassEditor_hiddenPassId">
                            <?php if ( function_exists( 'wp_nonce_field' ) ) { wp_nonce_field( 'laterpay_form' ); } ?>

                            <table class="lp_timePass_formColumn">
                                <tr>
                                    <td colspan="2">
                                        <?php tx_laterpay_helper_string::trEcho('The pass is valid for '); ?>
                                        <select name="duration" class="lp_js_switchTimePassDuration lp_input">
                                            <?php echo tx_laterpay_helper_timepass::getSelectOptions( 'duration' ); ?>
                                        </select>
                                        <select name="period" class="lp_js_switchTimePassPeriod lp_input">
                                            <?php echo tx_laterpay_helper_timepass::getSelectOptions( 'period' ); ?>
                                        </select>
                                        <?php tx_laterpay_helper_string::trEcho('and grants'); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <?php tx_laterpay_helper_string::trEcho('access to'); ?>
                                    </td>
                                    <td>
                                        <select name="access_to" class="lp_js_switchTimePassScope lp_input lp_u_w-1">
                                            <?php echo tx_laterpay_helper_timepass::getSelectOptions( 'access' ); ?>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    </td>
                                    <td class="lp_js_timePassCategoryWrapper">
                                        <input type="hidden" name="category_name" value="" class="lp_js_switchTimePassScopeCategory">
                                        <input type="hidden" name="access_category" value="" class="lp_js_timePassCategoryId">
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <?php tx_laterpay_helper_string::trEcho('The user pays'); ?>
                                        <input type="text"
                                                name="price"
                                                class="lp_js_timePassPriceInput lp_input lp_numberInput"
                                                value="<?php echo tx_laterpay_helper_view::formatNumber( tx_laterpay_helper_timePass::getDefaultOptions( 'price' ) ) ?>">
                                        <?php echo $laterpay['standard_currency']; ?>
                                        <?php tx_laterpay_helper_string::trEcho('later'); ?><div class="lp_toggle">
                                            <label class="lp_toggle_label lp_toggle_label_pass">
                                                <input type="checkbox"
                                                       name="revenue_model"
                                                       class="lp_js_timePassRevenueModelInput lp_toggle_input"
                                                       value="sis"
                                                       <?php if ( tx_laterpay_helper_timepass::getDefaultOptions( 'revenue_model' ) === 'sis' ) { echo 'checked'; } ?>>
                                                <span class="lp_toggle_text" data-on="" data-off=""></span>
                                                <span class="lp_toggle_handle"></span>
                                            </label>
                                        </div><?php tx_laterpay_helper_string::trEcho('immediately'); ?>
                                    </td>
                                </tr>
                            </table>

                            <table class="lp_timePass_formColumn">
                                <tr>
                                    <td>
                                        <?php tx_laterpay_helper_string::trEcho('Title'); ?>
                                    </td>
                                    <td>
                                        <input type="text"
                                                name="title"
                                                class="lp_js_timePassTitleInput lp_input lp_u_w-1"
                                                value="<?php echo tx_laterpay_helper_timePass::getDefaultOptions( 'title' ); ?>">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="lp_rowspan-label">
                                        <?php tx_laterpay_helper_string::trEcho('Description'); ?>
                                    </td>
                                    <td rowspan="2">
                                        <textarea
                                            name="description"
                                            class="lp_js_timePassDescriptionTextarea lp_timePass_descriptionInput lp_input lp_u_w-1">
                                            <?php echo tx_laterpay_helper_timePass::getDescription(); ?>
                                        </textarea>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    </td>
                                </tr>
                            </table>

                        </form>
                    </div>

                    <a href="#" class="lp_js_saveTimePass lp_saveLink button button-primary"><?php tx_laterpay_helper_string::trEcho('Save'); ?></a>
                    <a href="#" class="lp_js_cancelEditingTimePass lp_cancelLink lp_u_inlineBlock lp_u_pd-05" data-icon="e"><?php tx_laterpay_helper_string::trEcho('Cancel'); ?></a>
                    <a href="#" class="lp_js_editTimePass lp_changeLink lp_u_inlineBlock lp_u_pd-05 lp_u_hide" data-icon="d"><?php tx_laterpay_helper_string::trEcho('Change'); ?></a><br>
                    <a href="#" class="lp_js_deleteTimePass lp_deleteLink lp_u_inlineBlock lp_u_pd-05 lp_u_hide" data-icon="g"><?php tx_laterpay_helper_string::trEcho('Delete'); ?></a>

                    <div class="lp_js_voucherList"></div>
                </div>
            </div>
        </div>

    </div>
</div>
