<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<div class="lp_paidContent">
    <div class="lp_fullContent">
        <!-- <?php tx_laterpay_helper_string::trEcho('Preview a short excerpt from the paid post:'); ?> -->
        <?php echo tx_laterpay_helper_string::truncate(
                $content,
                tx_laterpay_helper_string::determineNumberOfWords( $content ),
                array(
                    'html'  => true,
                    'words' => true,
                )
            ); ?>
        <br>
        <?php tx_laterpay_helper_string::trEcho('Thanks for reading this short excerpt from the paid post! Fancy buying it to read all of it?'); ?>
    </div>
    <div class="lp_overlayText">
        <div class="lp_benefits">
            <header>
                <h2>
                    <span data-icon="a"></span>
                    <?php tx_laterpay_helper_string::trEcho('Read Now, Pay Later'); ?>
                </h2>
            </header>
            <ul class="lp_u_clearfix">
                <?php if ( $revenueModel == 'sis' ): ?>
                    <li class="lp_benefitBuyNow">
                        <h3><?php tx_laterpay_helper_string::trEcho('Buy Now'); ?></h3>
                        <p>
                            <?php tx_laterpay_helper_string::trEcho('Buy this post now with LaterPay and <br>pay with a payment method you trust.'); ?>
                        </p>
                    </li>
                    <li class="lp_benefitUseImmediately">
                        <h3><?php tx_laterpay_helper_string::trEcho('Read Immediately'); ?></h3>
                        <p>
                            <?php tx_laterpay_helper_string::trEcho('Immediately access your purchase. <br>You only buy this post. No subscription, no fees.'); ?>
                        </p>
                    </li>
                <?php else: ?>
                    <li class="lp_benefitBuyNow">
                        <h3><?php tx_laterpay_helper_string::trEcho('Buy Now'); ?></h3>
                        <p>
                            <?php tx_laterpay_helper_string::trEcho('Just agree to pay later.<br> No upfront registration and payment.'); ?>
                        </p>
                    </li>
                    <li class="lp_benefitUseImmediately">
                        <h3><?php tx_laterpay_helper_string::trEcho('Read Immediately'); ?></h3>
                        <p>
                            <?php tx_laterpay_helper_string::trEcho('Get immediate access to your purchase.<br> You are only buying this article, not a subscription.'); ?>
                        </p>
                    </li>
                    <li class="lp_benefitPayLater">
                        <h3><?php tx_laterpay_helper_string::trEcho('Pay Later'); ?></h3>
                        <p>
                            <?php tx_laterpay_helper_string::trEcho('Buy with LaterPay until you reach a total of 5 Euro.<br> Only then do you have to register and pay.'); ?>
                        </p>
                    </li>
                <?php endif; ?>
            </ul>
            <div>
                <div class="lp_u_clearfix lp_u_relative lp_u_m-t1 lp_u_m-b2">
                    <div>
                        <a data-is-in-visible-test-mode="<?php echo $isInVisibleTestMode; ?>" data-preview-as-visitor="<?php echo $previewAsVisitor; ?>" data-post-id="" data-laterpay="<?php echo $purchaseURL; ?>" data-icon="b" title="Buy now with LaterPay" class="lp_js_doPurchase lp_purchaseLink lp_button" href="#"><?php echo $price; ?><small>EUR</small></a>
                    </div>
                </div>
            </div>
            <div class="lp_poweredBy">
                powered by<span data-icon="a"></span>beta
            </div>
        </div>
    </div>
</div>
