<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<div class="lp_dropdown">
    <span class="lp_dropdown_currentItem"><?php tx_laterpay_helper_string::trEcho('all'); ?></span>
    <div class="lp_dropdown_list">
        <div class="lp_triangle lp_outerTriangle"><div class="lp_triangle"></div></div>
        <a href="#" class="lp_js_selectRevenueModel lp_dropdown_listItem lp_is-selected" data-revenue-model="all"><?php tx_laterpay_helper_string::trEcho('all'); ?></a>
        <a href="#" class="lp_js_selectRevenueModel lp_dropdown_listItem" data-revenue-model="ppu"><?php tx_laterpay_helper_string::trEcho('PPU'); ?></a>
        <a href="#" class="lp_js_selectRevenueModel lp_dropdown_listItem" data-revenue-model="sis"><?php tx_laterpay_helper_string::trEcho('SIS'); ?></a>
    </div>
</div>