<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<div class="lp_dropdown">
    <span class="lp_dropdown_currentItem"><?php tx_laterpay_helper_string::trEcho( '8 Day', 'laterpay' ); ?></span>
    <div class="lp_dropdown_list">
        <div class="lp_triangle lp_outerTriangle"><div class="lp_triangle"></div></div>
        <a href="#" class="lp_js_selectDashboardInterval lp_dropdown_listItem" data-interval="day"><?php tx_laterpay_helper_string::trEcho( '24 Hour', 'laterpay' ); ?></a>
        <a href="#" class="lp_js_selectDashboardInterval lp_dropdown_listItem lp_is-selected" data-interval="week"><?php tx_laterpay_helper_string::trEcho( '8 Day', 'laterpay' ); ?></a>
        <a href="#" class="lp_js_selectDashboardInterval lp_dropdown_listItem" data-interval="2-weeks"><?php tx_laterpay_helper_string::trEcho( '2 Week', 'laterpay' ); ?></a>
        <a href="#" class="lp_js_selectDashboardInterval lp_dropdown_listItem" data-interval="month"><?php tx_laterpay_helper_string::trEcho( '1 Month', 'laterpay' ); ?></a>
    </div>
</div>
