<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>
<?php

$disabled_class = '';
if ( $laterpay[ 'end_timestamp' ] > $laterpay[ 'interval_end' ] ) :
    $disabled_class = 'lp_is-disabled';
endif;
?>
<a href="#" id="lp_js_loadPreviousInterval" class="lp_prevNextLink lp_tooltip <?php echo $disabled_class; ?>" data-tooltip="<?php tx_laterpay_helper_string::trEcho('Show previous 8 days'); ?>">
    <div class="lp_triangle lp_triangle--left"></div>
</a>

<span id="lp_js_displayedInterval" data-interval-end-timestamp="<?php echo $laterpay[ 'end_timestamp' ]; ?>" data-start-timestamp="<?php echo $laterpay[ 'interval_start' ]; ?>">
    <?php if ( $GLOBALS['LANG']->lang == 'de' ): ?>
        <?php echo date( 'j.n.Y', $laterpay['interval_end'] ) . ' &ndash; ' . date( 'j.n.Y', $laterpay['interval_start'] ); ?>
    <?php else: ?>
        <?php echo date( 'Y-m-d', $laterpay['interval_end'] ) . ' &ndash; ' . date( 'Y-m-d', $laterpay['interval_start'] ); ?>
    <?php endif; ?>
</span>

<a href="#" id="lp_js_loadNextInterval" class="lp_prevNextLink lp_tooltip lp_is-disabled">
    <div class="lp_triangle lp_triangle--right"></div>
</a>
