<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<?php
    // plugin menu pointer
    if ( in_array( LaterPay_Controller_Admin::ADMIN_MENU_POINTER, $laterpay['pointers'] ) ):
        $pointer_content = '<h3>' . tx_laterpay_helper_string::tr('Welcome to LaterPay') . '</h3>';
        $pointer_content .= '<p>' . tx_laterpay_helper_string::tr('Set the most appropriate settings for you.') . '</p>';
?>
    <script>
        jQuery(document).ready(function($) {
            if (typeof(jQuery().pointer) !== 'undefined') {
                jQuery('#toplevel_page_laterpay-plugin')
                .pointer({
                    content : '<?php echo $pointer_content; ?>',
                    position: {
                        edge: 'left',
                        align: 'middle'
                    },
                    close: function() {
                        jQuery.post( ajaxurl, {
                            pointer: '<?php echo LaterPay_Controller_Admin::ADMIN_MENU_POINTER; ?>',
                            action: 'dismiss-wp-pointer'
                        });
                    }
                })
                .pointer('open');
            }
        });
    </script>
<?php endif; ?>
<?php
    // add / edit post page - pricing box pointer
    if ( in_array( LaterPay_Controller_Admin::POST_PRICE_BOX_POINTER, $laterpay['pointers'] ) ):
        $pointer_content = '<h3>' . tx_laterpay_helper_string::tr('Set a Price for this Post') . '</h3>';
        $pointer_content .= '<p>' . tx_laterpay_helper_string::tr('Set an <strong>individual price</strong> for this post here.<br>You can also apply <strong>advanced pricing</strong> by defining how the price changes over time.') . '</p>';
?>
    <script>
        jQuery(document).ready(function($) {
            if (typeof(jQuery().pointer) !== 'undefined') {
                jQuery('#lp_postPricing')
                .pointer({
                    content: '<?php echo $pointer_content; ?>',
                    position: {
                        edge: 'top',
                        align: 'middle'
                    },
                    close: function() {
                        jQuery.post( ajaxurl, {
                            pointer: '<?php echo LaterPay_Controller_Admin::POST_PRICE_BOX_POINTER; ?>',
                            action: 'dismiss-wp-pointer'
                        });
                    }
                })
                .pointer('open');
            }
        });
    </script>
<?php endif; ?>
<?php
    // add / edit post page - teaser content pointer
    if ( in_array( LaterPay_Controller_Admin::POST_TEASER_CONTENT_POINTER, $laterpay['pointers'] ) ):
    $pointer_content = '<h3>' . tx_laterpay_helper_string::tr('Add Teaser Content') . '</h3>';
    $pointer_content .= '<p>' . tx_laterpay_helper_string::tr('You?ll give your users a better impression of what they?ll buy, if you preview some text, images, or video from the actual post.') . '</p>';
?>
    <script>
        jQuery(document).ready(function($) {
            if (typeof(jQuery().pointer) !== 'undefined') {
                jQuery('#lp_postTeaser')
                .pointer({
                    content: '<?php echo $pointer_content; ?>',
                    position: {
                        edge: 'bottom',
                        align: 'left'
                    },
                    close: function() {
                        jQuery.post( ajaxurl, {
                            pointer: '<?php echo LaterPay_Controller_Admin::POST_TEASER_CONTENT_POINTER; ?>',
                            action: 'dismiss-wp-pointer'
                        });
                    }
                })
                .pointer('open');
            }
        });
    </script>
<?php endif; ?>
