<?php if ( ! defined( 'TYPO3_MODE' ) ) { die('Access denied.'); } ?>

<?php
    $title = sprintf(
        '%s<small>%s</small>',
        tx_laterpay_helper_view::formatNumber( $laterpay_pass['price'] ),
        $laterpay['standard_currency']
    );

    $period = tx_laterpay_helper_timepass::getPeriodOptions( $laterpay_pass['period'] );
    if ( $laterpay_pass['duration'] > 1 ) {
        $period = tx_laterpay_helper_timepass::getPeriodOptions( $laterpay_pass['period'], true );
    }

    $price = tx_laterpay_helper_view::formatNumber( $laterpay_pass['price'] );

    $access_type = tx_laterpay_helper_timepass::getAccessOptions( $laterpay_pass['access_to'] );
    $access_dest = tx_laterpay_helper_string::tr('on this website');
    $category = new stdClass();
    if ( $laterpay_pass['access_to'] != 0 ) {
        $access_dest = $category->name;
    }
?>

<div class="lp_js_timePass lp_timePass lp_timePass-<?php echo $laterpay_pass['pass_id']; ?>" data-pass-id="<?php echo $laterpay_pass['pass_id']; ?>">
    <section class="lp_timePass__front">
        <h4 class="lp_js_timePassPreviewTitle lp_timePass_title"><?php echo $laterpay_pass['title']; ?></h4>
        <p class="lp_js_timePassPreviewDescription lp_timePass_description"><?php echo $laterpay_pass['description']; ?></p>
        <div class="lp_timePass_actions">
            <a href="#" class="lp_js_doPurchase lp_purchaseLink lp_button" title="<?php echo tx_laterpay_helper_string::tr('Buy now with LaterPay'); ?>" data-icon="b" data-laterpay="<?php echo $laterpay_pass['url']?>" data-preview-as-visitor="<?php echo $laterpay['preview_post_as_visitor']?>" data-is-in-visible-test-mode = "<?php echo $laterpay['is_in_visible_test_mode'] ?>"><?php echo $title ?></a><a href="#" class="lp_js_flipTimePass lp_timePass_termsLink"><?php tx_laterpay_helper_string::trEcho('Terms'); ?></a>
        </div>
    </section>
    <section class="lp_timePass__back">
        <a href="#" class="lp_js_flipTimePass lp_timePass_frontsideLink"><?php tx_laterpay_helper_string::trEcho('Back'); ?></a>
        <table class="lp_timePass__conditions">
            <tr>
                <th><?php tx_laterpay_helper_string::trEcho('Validity') ?></th>
                <td>
                    <span class="lp_js_timePassPreviewValidity"><?php echo $laterpay_pass['duration'] . ' ' . $period; ?></span>
                </td>
            </tr>
            <tr>
                <th><?php tx_laterpay_helper_string::trEcho('Access to'); ?></th>
                <td>
                    <span class="lp_js_timePassPreviewAccess"><?php echo $access_type . ' ' . $access_dest; ?></span>
                </td>
            </tr>
            <tr>
                <th><?php tx_laterpay_helper_string::trEcho('Renewal') ?></th>
                <td>
                    <?php tx_laterpay_helper_string::trEcho('No automatic renewal'); ?>
                </td>
            </tr>
            <tr>
                <th><?php tx_laterpay_helper_string::trEcho('Price') ?></th>
                <td>
                    <span class="lp_js_timePassPreviewPrice"><?php echo $price . ' ' . $laterpay['standard_currency']; ?></span>
                </td>
            </tr>
        </table>
    </section>
</div>
