<?php ?>
<div class="lp_u_clearfix lp_u_relative lp_u_m-t1 lp_u_m-b2">
    <div>
        <a data-is-in-visible-test-mode="<?php echo $isInVisibleTestMode?>" data-preview-as-visitor="<?php echo $previewAsVisitor?>" data-post-id="" data-laterpay="<?php echo $purchaseURL ?>" data-icon="b" title="Buy now with LaterPay" class="lp_js_doPurchase lp_purchaseLink lp_button" href="#"><?php echo $price ?><small>EUR</small></a>
    </div>
</div>